version: '3.8'

services:
  bot:
    container_name: aldi-tg-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn run dev
  db:
    container_name: aldi-tg-bot-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes: 
  data: {}