version: '3.8'

services:
  aldi-bot:
    container_name: aldi-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
    depends_on:
      - aldi-pg
    env_file:
      - .env
  aldi-pg:
    container_name: aldi-pg
    image: postgres:13
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: aldi-bot_data