version: '3.8'

services:
  bot:
    container_name: aldi-tg-bot
    # restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    container_name: aldi-tg-bot-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes: 
  data: {}