version: '3.8'

services:
  telegraf:
    container_name: telegraf
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: aldi-bot_data