version: '3.8'

services:
  # bot:
  #   container_name: aldi-tg-bot
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
  #   ports:
  #     - ${PORT}:${PORT}
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/usr/src/app/src
  #     - ./nodemon.json:/usr/src/app/nodemon.json
  #   expose:
  #     - ${PORT}
  #   command: yarn run dev:migrate
  aldi-pg:
    container_name: aldi-pg
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes: 
  data: {}